server:
  port: 8021
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix-stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    hostname: ribbon
