server:
  port: 8761
eureka:
  instance:
    hostname: discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#eureka:
#instance:
#hostname: discovery # 指定该Eureka实例的主机名
#client:
#registerWithEureka: false
#fetchRegistry: false
#serviceUrl:
#defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#---
#spring:
#  profiles: peer1 # 指定profile=peer1
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: peer1 # 指定当profile=peer1时，主机名
#  client:
#    service-url:
#      defaultZone: http://peer2:8762/eureka/ # 将服务注册到peer2这个Eureka上?去
#
#---
#spring:
#  profiles: peer2 # 指定profile=peer2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: peer2 # 指定当profile=peer2时，主机名
#  client:
#    service-url:
#      defaultZone: http://peer1:8761/eureka/ # 将服务注册到peer2这个Eureka上?去
