server:
  port: 8021
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    # 此处，preferIpAddress不设置或者设为false，不能设为true，否则影响turbine的测试。
    #turbine存在的问题：eureka.instance.hostname?致时只能检测到?个节点，会造成turbine数据不完整
    hostname: ribbon
